/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-26: 20h: 7m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__0() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__1() ;

ATSstatic()
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__0__1() ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__6(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__2(atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__6__1(atstkind_t0ype(atstype_int)) ;

#if(0)
/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 154(line=7, offs=19) -- 164(line=7, offs=29)
*/
/*
local: 
global: plus1$0$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__0()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 148(line=7, offs=13) -- 164(line=7, offs=29)
*/
ATSINSflab(__patsflab_plus1):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 159(line=7, offs=24) -- 164(line=7, offs=29)
*/
ATSINSmove(tmpret0, PMVtmpltcst(g1int_add<S2Eextkind(atstype_int)>)(ATSPMVi0nt(0), ATSPMVi0nt(1))) ;

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 232(line=8, offs=24) -- 245(line=8, offs=37)
*/
/*
local: 
global: call_plus1$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 221(line=8, offs=13) -- 245(line=8, offs=37)
*/
ATSINSflab(__patsflab_call_plus1):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 237(line=8, offs=29) -- 245(line=8, offs=37)
*/
ATSINSmove(tmpret1, PMVtmpltcst(plus1<>)()) ;

ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1] */
#endif // end of [TEMPLATE]

/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 263(line=10, offs=17) -- 466(line=15, offs=2)
*/
/*
local: 
global: mainats_void_0$2$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret2) ;
ATStmpdec_void(tmp3) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp7) ;
ATStmpdec_void(tmp9) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 257(line=10, offs=11) -- 466(line=15, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 268(line=10, offs=22) -- 466(line=15, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 291(line=11, offs=22) -- 304(line=11, offs=35)
*/
ATSINSmove(tmp4, _057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__1()) ;

/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 281(line=11, offs=12) -- 305(line=11, offs=36)
*/
ATSINSmove_void(tmp3, atspre_print_int(tmp4)) ;

/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 281(line=11, offs=12) -- 305(line=11, offs=36)
*/
ATSINSmove_void(tmp7, atspre_print_newline()) ;

/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 349(line=13, offs=12) -- 451(line=14, offs=43)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 433(line=14, offs=25) -- 446(line=14, offs=38)
*/
ATSINSmove(tmp10, _057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__2(ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 423(line=14, offs=15) -- 447(line=14, offs=39)
*/
ATSINSmove_void(tmp9, atspre_print_int(tmp10)) ;

/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 423(line=14, offs=15) -- 447(line=14, offs=39)
*/
ATSINSmove_void(tmpret2, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 349(line=13, offs=12) -- 451(line=14, offs=43)
*/
/*
INSletpop()
*/
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 268(line=10, offs=22) -- 466(line=15, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret2) ;
} /* end of [mainats_void_0] */

/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 232(line=8, offs=24) -- 245(line=8, offs=37)
*/
/*
local: 
global: call_plus1$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 221(line=8, offs=13) -- 245(line=8, offs=37)
*/
ATSINSflab(__patsflab_call_plus1):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 237(line=8, offs=29) -- 245(line=8, offs=37)
*/
ATSINSmove(tmpret1__1, _057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__0__1()) ;

ATSfunbody_end()
ATSreturn(tmpret1__1) ;
} /* end of [_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__1] */

/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 154(line=7, offs=19) -- 164(line=7, offs=29)
*/
/*
local: 
global: plus1$0$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__0__1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 148(line=7, offs=13) -- 164(line=7, offs=29)
*/
ATSINSflab(__patsflab_plus1):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 159(line=7, offs=24) -- 164(line=7, offs=29)
*/
ATSINSmove(tmpret0__1, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(1))) ;

ATSfunbody_end()
ATSreturn(tmpret0__1) ;
} /* end of [_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__0__1] */

#if(0)
/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 371(line=13, offs=34) -- 381(line=13, offs=44)
*/
/*
local: 
global: plus1$6$0(level=1)
local: v$3447(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: v$3447(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__6(atstkind_t0ype(atstype_int) env0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 365(line=13, offs=28) -- 381(line=13, offs=44)
*/
ATSINSflab(__patsflab_plus1):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 376(line=13, offs=39) -- 381(line=13, offs=44)
*/
ATSINSmove(tmpret8, PMVtmpltcst(g1int_add<S2Eextkind(atstype_int)>)(env0, ATSPMVi0nt(1))) ;

ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__6] */
#endif // end of [TEMPLATE]

/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 232(line=8, offs=24) -- 245(line=8, offs=37)
*/
/*
local: 
global: call_plus1$1$2(level=1)
local: v$3447(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: v$3447(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__2(atstkind_t0ype(atstype_int) env0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 221(line=8, offs=13) -- 245(line=8, offs=37)
*/
ATSINSflab(__patsflab_call_plus1):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 237(line=8, offs=29) -- 245(line=8, offs=37)
*/
ATSINSmove(tmpret1__2, _057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__6__1(env0)) ;

ATSfunbody_end()
ATSreturn(tmpret1__2) ;
} /* end of [_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__call_plus1__1__2] */

/*
/home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 371(line=13, offs=34) -- 381(line=13, offs=44)
*/
/*
local: 
global: plus1$6$1(level=2)
local: v$3447(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: v$3447(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_int)
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__6__1(atstkind_t0ype(atstype_int) env0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 365(line=13, offs=28) -- 381(line=13, offs=44)
*/
ATSINSflab(__patsflab_plus1):
/*
emit_instr: loc0 = /home/kiwamu/src/practice-ats/localized-template/testtemp.dats: 376(line=13, offs=39) -- 381(line=13, offs=44)
*/
ATSINSmove(tmpret8__1, atspre_g1int_add_int(env0, ATSPMVi0nt(1))) ;

ATSfunbody_end()
ATSreturn(tmpret8__1) ;
} /* end of [_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__plus1__6__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload0(
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_kiwamu_057_src_057_practice_055_ats_057_localized_055_template_057_testtemp_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
